//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criterio()
        {
            this.CriterioLibro = new HashSet<CriterioLibro>();
        }
    
        public int id { get; set; }
        public string codigo_criterio { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public Nullable<bool> requiere_cliente { get; set; }
        public Nullable<bool> prohibe_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriterioLibro> CriterioLibro { get; set; }
    }
}
