//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDescuento
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<bool> aplica_genero { get; set; }
        public Nullable<int> genero_fk { get; set; }
        public Nullable<bool> aplica_autor { get; set; }
        public Nullable<int> autor_fk { get; set; }
        public decimal descuento { get; set; }
        public bool estatus { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
