//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCompraVentaLibro
    {
        public int id { get; set; }
        public int libro_fk { get; set; }
        public decimal precio_unitario_compra { get; set; }
        public decimal precio_unitario_venta { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public int cantidad_comprada { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
    
        public virtual Libro Libro { get; set; }
    }
}
