//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.AutorLibro = new HashSet<AutorLibro>();
            this.CriterioLibro = new HashSet<CriterioLibro>();
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetalleOrden = new HashSet<DetalleOrden>();
            this.HistorialCompraVentaLibro = new HashSet<HistorialCompraVentaLibro>();
        }
    
        public int id { get; set; }
        public string isbn { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public int cantidad_stock { get; set; }
        public string titulo { get; set; }
        public int genero_fk { get; set; }
        public Nullable<int> criterio_acaba { get; set; }
        public Nullable<int> criterio_esperado { get; set; }
        public decimal monto_unitario { get; set; }
        public bool restringido { get; set; }
        public bool prohibido { get; set; }
        public bool activo { get; set; }
        public int proveedor_fk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorLibro> AutorLibro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriterioLibro> CriterioLibro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrden { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCompraVentaLibro> HistorialCompraVentaLibro { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
