//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.DetalleOrden = new HashSet<DetalleOrden>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int id { get; set; }
        public Nullable<int> cliente_fk { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public bool pago_efectivo { get; set; }
        public bool pago_tarjeta { get; set; }
        public decimal monto_pago_efectivo { get; set; }
        public decimal monto_pago_tarjeta { get; set; }
        public int caja_fk { get; set; }
        public int usuario_fk { get; set; }
        public decimal cambio_dinero { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
