//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroCierre
    {
        public int id { get; set; }
        public int registro_calendario_fk { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public decimal monto_caja { get; set; }
        public decimal monto_cierre { get; set; }
    
        public virtual RegistroCaja RegistroCaja { get; set; }
    }
}
