//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroCaja()
        {
            this.DetalleOrden = new HashSet<DetalleOrden>();
            this.RegistroCierre = new HashSet<RegistroCierre>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_calendario { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public decimal monto_inicial { get; set; }
        public bool vigente { get; set; }
        public int caja_fk { get; set; }
    
        public virtual Caja Caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroCierre> RegistroCierre { get; set; }
    }
}
