//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genero_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefono()
        {
            this.TelefonoCliente = new HashSet<TelefonoCliente>();
        }
    
        public int id { get; set; }
        public int tipo_telefono_fk { get; set; }
        public string numero { get; set; }
    
        public virtual TipoTelefono TipoTelefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonoCliente> TelefonoCliente { get; set; }
    }
}
